@echo off
echo 🚀 Starting Insight Studio Backend...
echo 📦 Installing dependencies...
pip install -r requirements.txt

echo 🗄️ Initializing database...
python -c "from storage import storage; print('✅ Database initialized')"

echo 🌐 Starting server...
uvicorn main:app --reload --host 0.0.0.0 --port 8000